[package]
name = "pyo3-chrono"
version = "0.1.0"
authors = ["kangalioo <jannik.a.schaper@web.de>"]
edition = "2018"

[dependencies]
# pyo3 = "0.13"
pyo3 = { git = "https://github.com/kangalioo/pyo3", branch = "datetime_with_fold"}
chrono = "0.4"